name: Manual workflow
on:
  pull_request:
    types: [labeled]

jobs:
  build:
    name: On Label
    # This job runs on Linux
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'run integration tests' )
    steps:
      - name: Echo the Github action context
        run: echo 'Context ${{ toJson(github) }}.'
